// Single source of truth for permission keys, enforced by PermissionsGuard +
// @RequirePermission on every guarded route. Previously duplicated between
// Rust (models.rs PERMISSION_CATALOG) and TS by hand; now that cloud-api is
// the sole backend, this is the only copy.
export const PERMISSION_CATALOG = [
  "students.view",
  "students.create",
  "students.edit",
  "students.delete",
  "admissions.view",
  "admissions.create",
  "admissions.confirm",
  "attendance.mark",
  "attendance.view",
  "fees.view",
  "fees.manage_structures",
  "fees.generate_invoices",
  "fees.void_invoice",
  "fees.record_payment",
  "exams.view",
  "exams.manage_subjects",
  "exams.manage_exams",
  "exams.enter_marks",
  "houses.view",
  "houses.manage_teams",
  "houses.manage_points",
  "library.view",
  "library.manage_catalog",
  "library.manage_issues",
  "transport.view",
  "transport.manage_routes",
  "transport.manage_assignments",
  "staff.view",
  "staff.manage_profile",
  "staff.manage_assignments",
  "staff_attendance.mark",
  "staff_attendance.view",
  "payroll.view",
  "payroll.view_own",
  "payroll.manage_salary_structure",
  "payroll.generate",
  "payroll.finalize",
  "payroll.manage_runs",
  "academic_setup.view",
  "academic_setup.manage_school_details",
  "academic_setup.manage_sessions",
  "academic_setup.manage_classes",
  "academic_setup.manage_sections",
  "academic_setup.promote",
  "master_data.view",
  "master_data.manage_gender",
  "master_data.manage_blood_group",
  "master_data.manage_religion",
  "master_data.manage_nationality",
  "master_data.manage_mother_tongue",
  "master_data.manage_student_category",
  "master_data.manage_guardian_relation",
  "master_data.manage_staff_category",
  "master_data.manage_fee_category",
  "roles.manage",
  "users.manage",
  "audit.view",
] as const;

export type PermissionKey = (typeof PERMISSION_CATALOG)[number];

// Human-readable labels for the Roles admin UI's permission matrix, served
// via GET /permissions/catalog alongside the raw keys. Kept as a separate
// map (rather than folded into PERMISSION_CATALOG) so the catalog itself
// stays a flat string tuple -- PermissionKey and everything typed against it
// depends on that shape.
export const PERMISSION_LABELS: Record<PermissionKey, { label: string; description?: string }> = {
  "students.view": { label: "View students" },
  "students.create": { label: "Create students" },
  "students.edit": { label: "Edit students" },
  "students.delete": { label: "Delete students" },
  "admissions.view": { label: "View admissions" },
  "admissions.create": { label: "Create admissions" },
  "admissions.confirm": { label: "Confirm admissions" },
  "attendance.mark": { label: "Mark attendance" },
  "attendance.view": { label: "View attendance" },
  "fees.view": { label: "View fees & invoices" },
  "fees.manage_structures": { label: "Manage fee structures" },
  "fees.generate_invoices": { label: "Generate invoices" },
  "fees.void_invoice": { label: "Void invoices" },
  "fees.record_payment": { label: "Record/reverse payments" },
  "exams.view": { label: "View exams & report cards" },
  "exams.manage_subjects": { label: "Manage subjects" },
  "exams.manage_exams": { label: "Manage exams (incl. back-paper)" },
  "exams.enter_marks": { label: "Enter marks" },
  "houses.view": { label: "View houses & leaderboard" },
  "houses.manage_teams": { label: "Manage house teams & student assignment" },
  "houses.manage_points": { label: "Award/deduct house points" },
  "library.view": { label: "View library" },
  "library.manage_catalog": { label: "Manage book catalog" },
  "library.manage_issues": { label: "Issue/return books" },
  "transport.view": { label: "View transport" },
  "transport.manage_routes": { label: "Manage routes & stops" },
  "transport.manage_assignments": { label: "Assign students to transport" },
  "staff.view": { label: "View staff" },
  "staff.manage_profile": { label: "Manage staff profiles" },
  "staff.manage_assignments": { label: "Manage teaching assignments" },
  "staff_attendance.mark": { label: "Mark staff attendance" },
  "staff_attendance.view": { label: "View staff attendance" },
  "payroll.view": { label: "View payroll" },
  "payroll.view_own": { label: "View own payslips" },
  "payroll.manage_salary_structure": { label: "Manage salary structures" },
  "payroll.generate": { label: "Generate payroll runs" },
  "payroll.finalize": { label: "Finalize payroll & mark paid" },
  "payroll.manage_runs": { label: "Delete/reopen payroll runs" },
  "academic_setup.view": { label: "View academic setup" },
  "academic_setup.manage_school_details": { label: "Manage school/branch details" },
  "academic_setup.manage_sessions": { label: "Manage academic sessions" },
  "academic_setup.manage_classes": { label: "Manage classes" },
  "academic_setup.manage_sections": { label: "Manage sections" },
  "academic_setup.promote": { label: "Promote students" },
  "master_data.view": { label: "View master data" },
  "master_data.manage_gender": { label: "Manage master data: Gender" },
  "master_data.manage_blood_group": { label: "Manage master data: Blood group" },
  "master_data.manage_religion": { label: "Manage master data: Religion" },
  "master_data.manage_nationality": { label: "Manage master data: Nationality" },
  "master_data.manage_mother_tongue": { label: "Manage master data: Mother tongue" },
  "master_data.manage_student_category": { label: "Manage master data: Student category" },
  "master_data.manage_guardian_relation": { label: "Manage master data: Guardian relation" },
  "master_data.manage_staff_category": { label: "Manage master data: Staff category" },
  "master_data.manage_fee_category": { label: "Manage master data: Fee category" },
  "roles.manage": { label: "Manage roles & permissions" },
  "users.manage": { label: "Manage user logins" },
  "audit.view": { label: "View audit log" },
};

export const TOGGLEABLE_MODULES = [
  "attendance",
  "fees",
  "exams",
  "library",
  "transport",
  "houses",
  "id_cards",
  "payroll",
] as const;

export type ToggleableModule = (typeof TOGGLEABLE_MODULES)[number];

// System roles seeded for every new tenant, each with a fixed permission
// set (matches prisma/seed.ts's DEFAULT_ROLES exactly -- this is the shared
// source both read from). Custom roles an admin creates via RolesModule are
// unrestricted.
export const SYSTEM_ROLE_PERMISSIONS: Record<string, readonly PermissionKey[]> = {
  super_admin: PERMISSION_CATALOG,
  branch_admin: PERMISSION_CATALOG.filter((key) => key !== "roles.manage"),
  accountant: [
    "fees.view",
    "fees.manage_structures",
    "fees.generate_invoices",
    "fees.void_invoice",
    "fees.record_payment",
    "payroll.view",
    "payroll.generate",
    "payroll.finalize",
    "students.view",
  ],
  teacher: [
    "attendance.mark",
    "attendance.view",
    "exams.view",
    "exams.enter_marks",
    "students.view",
    "staff_attendance.view",
    "payroll.view_own",
  ],
  front_desk: [
    "admissions.view",
    "admissions.create",
    "admissions.confirm",
    "students.view",
    "students.create",
    "students.edit",
    "library.view",
    "library.manage_issues",
  ],
};
